### ISSUE TITLE
Return (Enter) does not work after sudo su - <other user>

### ISSUE THREAD

**Issue by maartenbakx** [GoogleCloudPlatform/iap-desktop#471]
Expected behavior:
* Step 1: Within the SSH session switch from own named user to another user. sudo su - wwdadm
* Step 2: Execute command, for example cd /usr/sap and hit Enter button. Command gets executed.
* ...

Observed behavior:
* Step 1: Within the SSH session switch from own named user to another user. sudo su - wwdadm
* Step 2: Execute command, for example cd /usr/sap and hit Enter button. Nothing happens.
* ...

Installed version: 2.15.579.0
.NET Version: 4.7.3740.0
OS Version: Microsoft Windows NT 10.0.17763.0

**Comment by jpassing** [comment]
That's odd... I tried to reproduce this, but step 2 always works fine for me. A few questions:

* Does the same happen when you run `sudo su wwdadm` (i.e., without the `-`)? If yes, it might have something to do with `wwdadm`'s environment or `$PS1`.
* Does the same happen with other users?
* Are you using `bash`, or any other shell? 
* Where does the caret gets stuck, on the same line?

**Comment by maartenbakx** [comment]
Hi Johannes,

Apologies for the late reply. See my answers in bold below.

Kind Regards,

Maarten Bakx

Op di 27 apr. 2021 om 10:33 schreef Johannes Passing <
***@***.***>:

**Comment by jpassing** [comment]
The issue is probably caused by an xterm control sequence that IAP Desktop fails to parse properly, or that is somehow incomplete. 

To find out what sequence is causing the issue, it would be very helpful if you could provide a capture of what IAP Desktop received from the server:

1. Install [IapDesktop-2.16.605.msi.zip](https://github.com/GoogleCloudPlatform/iap-desktop/files/6415986/IapDesktop-2.16.605.msi.zip), which is the latest build from `master`.
2. Enable logging by clicking **Tools > Enable logging** .
3. Connect to the VM and reproduce the issue.
4. Right-click the tab while holding the Shift key, then click **Copy received data**:
    ![image](https://user-images.githubusercontent.com/5724941/116900547-25aadc80-ac39-11eb-8ce3-8cc52a48aa1f.png)

5. Paste the clipboard context into a text file and share it here or send it to iap-desktop@google.com. Please make sure the capture does not contain any sensitive information.

(Previously, the **Copy received data** command was only available in Debug builds, that's the reason for the new build)

**Comment by jpassing** [comment]
Hi Maarten,

if you have the time, could you try reproducing the issue and sharing the captured data? I'd like to fix this issue, but I am still having trouble reproducing it.

Thanks!

**Comment by jpassing** [comment]
This might be related to (and fixed by) #492

**Comment by maartenbakx** [comment]
Hi Johannes,

OK, is the fix already in the newest installation package? I just updated
to below version and the issue still exist.

[image: image.png]

Op do 13 mei 2021 om 15:57 schreef Johannes Passing <
***@***.***>:

**Comment by jpassing** [comment]
Sorry, the fix I mentioned in my previous comment went into release [2.17.616](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.17.616), which I released just now.

Could you give this version a try? If it's still broken, sharing the sent and received data as described in a previous comment would be helpful.

**Comment by maartenbakx** [comment]
Hi Johannes,

thanks a lot! It works now. This makes my life a lot easier :-)

Kind Regards,

Maarten Bakx

Op vr 14 mei 2021 om 10:13 schreef Johannes Passing <
***@***.***>:

**Comment by jpassing** [comment]
Great, thanks for confirming!

I am closing this issue then.
